final_task/config/routes.rb
FinalTask::Application.routes.draw do
  get "sessions/new"

    
     
     get "sign_up" => "users#new", :as => "sign_up"
     resources :users
      
     get "log_in" => "sessions#new", :as => "log_in" 
     resources :sessions
     
     get "log_out" => "sessions#destroy", :as => "log_out"
     
     namespace :admin do
       resources :categories
     end
     
     resources :comments
     resources :articles
     resources :products
     resources :homes
     resources :categories
     
     root :to => 'homes#index'   
     

  match ':controller(/:action(/:id(.:format)))'
end

final_task/app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products,  :dependent => :destroy
  has_many :child_categories, :dependent => :destroy,
           :class_name => "Category",
           :foreign_key => "parent_id"
  
  belongs_to :parent_category,
             :class_name => "Category",
             :foreign_key => "parent_id"
  scope :parent_cat, where("parent_id is NULL ")
end

final_task/app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::ApplicationController
  before_filter :require_admin_login
  
  def index
    @categories= Category.all
  end
  
  def new
    @category= Category.new 
    @parent_category = Category.where(["parent_id IS NULL"]).map{|x| [x.name, x.id ]}
  end
  
  def create
    @category= Category.new(params[:category])
    if @category.save
      flash[:notice] = 'Article was successfully created.'
      redirect_to admin_categories_path
    else
      flash[:error] = 'Article was failed to create.'
      render :new
    end
  end
  
  def edit
    @category = Category.find_by_id(params[:id])
    @parent_category = Category.where(["parent_id IS NULL"]).map{|x| [x.name, x.id ]}
  end
  
  def update
    @category = Category.find_by_id(params[:id])
    if @category.update_attributes(params[:category])
      flash[:notice] = "Category was successfully updated"
      redirect_to admin_categories_path
    else
      flash[:error] = "Category was failed to update"
      render :edit
    end
  end
  
  def destroy
   @category = Category.find_by_id(params[:id])
    puts @category.destroy
    flash[:notice] = "Article was successfully deleted"
    redirect_to admin_categories_path
  end
  
end

final_task/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
    @parent= Category.parent
  end
  
  def show
    @products = Product.find_all_by_category_id(params[:id])
  end
  

end

final_task/app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

final_task/app/helpers/categories_helper.rb
module CategoriesHelper
end

final_task/app/views/categories/_index.html.erb
<% @parent= Category.parent_cat %>
<nav>
<% @parent.each do |parent|  %>
  <ul> 
    <%= parent.name %>
     <% parent.child_categories.each do |child| %>
       <li> <%= link_to child.name, category_path(child.id) %></li>
    <% end %>
    
  </ul>

<%end %>
</nav>

final_task/app/views/categories/index.html.erb
<% @parent.each do |parent|  %>
  <ul> 
    <%= parent.name %>
     <% parent.child_categories.each do |child| %>
       <li> <%= child.name %> </li>
    <% end %>
    
  </ul>

<%end %>

final_task/app/views/categories/show.html.erb
<h1>User Products</h1>
<!-- <p><%= flash[:error] || flash[:notice] %></p> -->
<p>Products list from DB</p>
<table>
  <tr>
	<th>Name</th>
	<th>Description</th>
	<th>Price</th>
	<th>Weight</th>
	<th>Category</th>
  </tr>
  <tr>
	<% @products.each do |product| %>
	<td><%= product.name %></td>
	<td><%= product.description %></td>
	<td><%= product.price %></td>
	<td><%= product.weight %></td>
	<td><%= product.category_id %></td>

	<td>
	  <%= link_to "Show", product_path(product.id) %>
	  <% unless current_user.nil?%>
        <% if current_user.is_admin? %>
	      <%= link_to "Edit", edit_product_path(product.id) %>
	      <%= link_to 'Delete', product_path(product.id) , confirm: 'Do you want to delete this product?', method: :delete %>
	    <% else%> 
          <% if product.user_id == current_user.id %> 
	      <%= link_to "Edit", edit_product_path(product.id) %>
	      <%= link_to 'Delete', product_path(product.id) , confirm: 'Do you want to delete this product?', method: :delete %>
	    <% end %>
      <%end%>
   <%end%>  
	</td>
  </tr>
  <% end %>
</table>     
</ul>
<%= link_to "Create New product", new_product_path %>