try_1/config/routes.rb
Try1::Application.routes.draw do
  get "comments/new"

  get "sessions/new"

  get "users/new"

   resources :articles
   
   
   get "sign_up" => "users#new", :as => "sign_up"
   root :to => "users#new"
   resources :users
   
   get "log_in" => "sessions#new", :as => "log_in" 
   get "log_out" => "sessions#destroy", :as => "log_out"
   resources :sessions
   
   resources :comments
   
   namespace :admin do
     resources :articles
   end
   
   namespace :admin do
     resources :comments
   end

   match ':controller(/:action(/:id(.:format)))'
end

try_1/app/models/article.rb
class Article < ActiveRecord::Base
 has_many :comments
 
 belongs_to :user
 
 scope :rating_is_and_above, lambda{|rate| where("rating >= ?", rate) } 
 
 validates :title, :presence => true,
                   :uniqueness => true



end

try_1/app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < Admin::ApplicationController
  before_filter :require_admin_login
   before_filter :find_article, :only => [:show, :edit, :update, :destroy]

 
  def index
    @articles = Article.all
  end
  
  def new
     @article =Article.new
  end
  
  def show
     @comments = @article.comments
     @comment = @article.comments.new
  end
  
  def create
    @article.save
    if @article.save
      flash[:notice] = 'Article was successfully created.'
      redirect_to admin_articles_path
    else
      flash[:error] = 'Article was failed to create.'
      render :new
    end
 
  end
  
  def edit
    @article = Article.find_by_id(params[:id])
    
  end
  
  def update
    if @article.update_attributes(params[:article])
       flash[:notice] = 'Article was successfully updated.'
       redirect_to admin_articles_path
    else
      flash[:error] = 'Article was failed to updated.'
      render :edit
    end
  end
  
  def destroy
    @article.destroy
    
    redirect_to admin_articles_path
  end
  
  private
    def find_article
      @article = Article.find_by_id(params[:id])
       if @article.nil? 
        flash[:error] = 'Article was not found.'
        redirect_to admin_articles_path
      end
    end
  
end

try_1/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_filter :find_article, :only => [:show, :edit, :update, :destroy]
  #before_filter :your_article, :only => [ :edit, :destroy]
  before_filter :require_login, :only => [:new, :create, :edit, :update, :delete]

  def index
    @articles = Article.all
  end
  
  def new
     @article =Article.new
  end
  
  def show
 
     @article = Article.find_by_id(params[:id])   
     @comments = @article.comments
     @comment = @article.comments.new
  end
  
  def create
    @article =Article.new(params[:article])
    
    @article.save
    if @article.save
      flash[:notice] = 'Article was successfully created.'
      redirect_to articles_path
    else
      flash[:error] = 'Article was failed to create.'
      render :new
    end
 
  end
  
  def edit
    @article = Article.find_by_id(params[:id])
    
  end
  
  def update
    @article = Article.find_by_id(params[:id])

    if @article.update_attributes(params[:article])
       flash[:notice] = 'Article was successfully updated.'
       redirect_to articles_path
    else
      flash[:error] = 'Article was failed to updated.'
      render :edit
    end
  end
  
  def destroy
    @article = Article.find_by_id(params[:id])
    @article.destroy
    
    redirect_to articles_path
  end
  
  private
    def find_article
       if Article.find_by_id(params[:id]).nil? 
        flash[:error] = 'Article was not found.'
        redirect_to articles_path
      end
    end
    
   # def your_article
    # user = User.find_by_email(current_user.email)
     # unless @article.user_id == user.id
      #  flash[:notice] = " It's not your article !!!"
       # redirect_to articles_path
      #end
    #end 
end

try_1/app/helpers/admin/articles_helper.rb
module Admin::ArticlesHelper
end

try_1/app/views/articles/_comments.html.erb
 <% comments.each do |comment| %>
         <%= comment.content %><br />
  <% end %>

try_1/app/views/articles/edit.html.erb
<html>
  <body>
    <h1> Buat Artikel Baru <h1>
    <%= form_for @article do |n| %>
      <% if @article.errors.any? %>
        <div id="errorExplanation">
        <p>
           <%= pluralize(@article.errors.count, "error") %> prohibited this user from being saved:
        </p>
        <ul>
           <% @article.errors.full_messages.each do |msg| %>
           <li><%= msg %></li>
           <% end %>
        </ul>
        </div>
      <% end %>
    
    <ul>
      <li>
        <%= n.label :title  %>
        <%= n.text_field :title  %>
      </li>
      
      <li>
        <%= n.label :body  %>
        <%= n.text_area :body  %>
      </li>
      
      <li>
        <%= n.label :rating  %>
        <%= n.text_field :rating  %>
      </li>
      
      <li>
        <%= n.submit %>
      </li>
    </ul>
     
    
    <% end %>
    <%= link_to 'Back', articles_path %>
    
    
  </body>
</html>

try_1/app/views/articles/index.html.erb
   <p>
  <%= flash[:error]  %>
  <%= flash[:notice] %>
    </p>
    <h1> Artikel Terkini </h1>
    <table>
      <% @articles.each do |article|   %>
       <tr> 
         <td> <%= article.title %> </td> <td></td> 
         <td> <%= article.body %> </td> 
         <td> <%= article.rating %> </td>
         <td> <%= link_to "Tampil", article_path(article.id) %> </td>
              <% unless current_user.nil?%>
                <% if current_user.is_admin? %>
                  <td> <%= link_to "Edit",  edit_article_path(article.id) %> </td>
                  <td> <%= link_to "Hapus", article_path(article.id), confirm: 'Apakah Anda Yakin?', method: :delete %> </td> 
                <% else%> 
                  <% user = User.find_by_email(current_user.email) %>
                  <% if a.user_id == user.id %> 
                    <td>
                    <%= link_to "Edit", edit_article_path(article.id) %>
                    </td> 
                    <td>
                    <%= link_to "Hapus", article_path(article.id), confirm: 'Apakah Anda Yakin?', method: :delete %>
                    </td>
                  <% end %>
                <%end%>
              <%end%>  
         
         
        </tr>
      <% end %>
    </table>
    <%= link_to "New", new_article_path %>
 

try_1/app/views/articles/new.html.erb
<html>
  <body>
    <h1> Buat Artikel Baru <h1>
    <%= form_for @article do |n| %>
    
      <% if @article.errors.any? %>
        <div id="errorExplanation">
        <p>
           <%= pluralize(@article.errors.count, "error") %> prohibited this user from being saved:
        </p>
        <ul>
           <% @article.errors.full_messages.each do |msg| %>
           <li><%= msg %></li>
           <% end %>
        </ul>
        </div>
      <% end %>
    
    <ul>
      <li>
        <%= n.label :title  %>
        <%= n.text_field :title  %>
      </li>
      
      <li>
        <%= n.label :body, "ISI" %>
        <%= n.text_area :body  %>
      </li>
      
      <li>
        <%= n.label :rating  %>
        <%= n.text_field :rating  %>
      </li>
        <% user = User.find_by_email(current_user.email) %>
        
        <%= n.hidden_field :user_id, :value => user.id %>
      
      <li>
        <%= n.submit %>
      </li>
    </ul>
    
    <% end %>
     <%= link_to 'Back', articles_path %>
    
    
  </body>
</html>

try_1/app/views/articles/show.html.erb
<html>
  <body>
	<p> <%= flash[:error]  %>
        <%= flash[:notice] %> </p>  
    <h1>Showing Article</h1>
    <p>
      <b>Title :</b>
      <%= @article.title %>
    </p>

    <p>
      <b>Body :</b>
      <%= @article.body %>
    </p>

    <p>
      <b>Rating :</b>
      <%= @article.rating %>
    </p>
    
    <!--bagian ini untuk menampilkan comment yang dimiliki oleh article tersebut -->
    <div id="comments_show">
      <%= render :partial => "comments", :locals => {:comments => @comments}  %>
    </div><br /><br />
    
    <div id="comment_content">  
      <% unless(current_user.nil?)%> 
        <%= form_for @comment, :url => comments_path, :remote => true  do  |f| -%>
          <%= f.text_area :content %>
          <%= f.hidden_field :article_id, :value => @article.id %>
          <%= submit_tag "comment" %>
        <% end %>  
      <% end %>
    </div>


    <%= link_to 'Back', articles_path %>
  </body>
</html>