final_task/config/routes.rb
FinalTask::Application.routes.draw do
  get "sessions/new"

    
     
     get "sign_up" => "users#new", :as => "sign_up"
     resources :users
      
     get "log_in" => "sessions#new", :as => "log_in" 
     resources :sessions
     
     get "log_out" => "sessions#destroy", :as => "log_out"
     
     namespace :admin do
       resources :categories
     end
     
     resources :comments
     resources :articles
     resources :products
     resources :homes
     resources :categories
     
     root :to => 'homes#index'   
     

  match ':controller(/:action(/:id(.:format)))'
end

final_task/app/views/layouts/_side.html.erb
<nav>
  <ul>
    <li><a><%= link_to "Edit Profile", edit_user_path(current_user.id) %> </a> </li>
    <li><a><%= link_to "Sell Product", new_product_path %> </a> </li>
    <li><a><%= link_to "Share an Article", new_article_path %> </a> </li>
    <li><a><%= link_to "Logut", log_out_path %> </a> </li>
  </ul>
</nav>

final_task/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FinalTask</title>
  <%= stylesheet_link_tag    "application" %>
  <%= stylesheet_link_tag    "style" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">	
    <header>	
      <h1>Welcome to my  Store </h1>
      <%= flash[:error]%>
      <nav>
		<ul>
	      <li>
			<a>    
	        <% if current_user.nil? %>
	          <%= link_to "Sign up", sign_up_path %>
	        <% else %>
	          <%= link_to "Home", root_path %>  
	        <% end %>
	        </a>
	      </li>
	      <li>  	
	        <a> <%= link_to "Products", products_path %> </a>
	     </li>
	      <li>  
	        <a> <%= link_to "Article", articles_path %> </a>
	      </li>  
	      <% unless current_user.nil?%>
	        <% if current_user.iss_admin %>
	        <li> <a> <%= link_to "Categories", admin_categories_path %> </a> </li>   
	        <%end%>
	      <%end%>
	    </ul>	
	  </nav>	
    </header>
    <aside>
	      <%= raw(welcome_text) %>
	      <% if current_user.nil? %>
	        <%= render :partial => "sessions/new" %>
          <% else %>
            <%= render :partial => "layouts/side" %>
            <%= render :partial => "categories/index" %>
            <div id="listProduct">
              <ul>
              </ul>
            </div> 
          <% end %>
	   
	  </aside> 
	  
	  <div id="content">  	  
        <%= yield %>
      </div>
      
    
  </div>
</body>
</html>